openapi: 3.0.0
servers:
  - url: /v1
info:
  description: This is a Birdie Test API
  version: "1.0.0"
  title: Birdie Test API
  contact:
    email: pmm26@protonmail.com

tags:
  - name: events
    description: List of Events 

paths: {}

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
      
  schemas:
    Event:
      type: object
      required:
        - id
        - name
        - manufacturer
        - releaseDate
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: Widget Adapter
        releaseDate:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'