apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-backend
  namespace: birdie
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
  selector:
    matchLabels:
      app: nodejs-backend
  template:
    metadata:
      labels:
        app: nodejs-backend
    spec:
      containers:
        - name: backend
          image: registry.gitlab.com/xdpedrox/birdietest/main:back-latest
          ports:
            - containerPort: 80
          env:
            - name: API_KEY
              value: birdiekey
            - name: DB_USER
              value: test-read
            - name: PORT
              value: "80"
            - name: BASE_URL
              value: "http://birdieapi.prck.me"

          resources: {}
      restartPolicy: Always
# kubectl set image deployments/nodejs-backend backend=registry.gitlab.com/xdpedrox/birdietest/main:back-0c638e8c8ceba6572dfeda3277f2de782c0dcd13 -n birdie